# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

# Benchtop provisioning orchestrator configuration files.
exports_files([
    "emulation_open.hjson",
    "ot00.hjson",
    "ot00_staging.hjson",
])
